### ISSUE TITLE
question

### ISSUE THREAD

**Issue by unnir** [ourfool/picture-to-gds#2]
sorry for opening the issue, but I have a simple question.

I want to convert GDSII to image, or better to say multidimensional array (where channels are layers from a gdsii file).   

Is it possible to make it with your script? If not, any ideas where to look for the solution?

**Comment by ourfool** [comment]
Hello.
This script is only to convert image to GDSII, so it cannot make image from GDSII.
That aside, it seems to be possible to write a simple python script to convert GDSII to image.
I think the page shown in below would be helpful.
http://boolean.klaasholwerda.nl/interface/bnf/gdsformat.html
