### ISSUE TITLE
image.gds file opening error in Klayout

### ISSUE THREAD

**Issue by qd2d** [ourfool/picture-to-gds#4]
I ran the code picToGDS.py in PyCharm and successfully produced a image.bmp file and image.gds file of about 574 kB in size. However, when I try to open the gds file with Klayout 0.25.9 I get an error: "Internal error: ../ ../ ../src/db/db/db Trans.h:1612 mag>0.0 was not true".  

When I tried commenting out lines 54 and 55:
```
scaledGrid = core.CellReference(
        grid, origin=(0, 0), magnification=(float)(sizeOfTheCell))
```

and modified line 53 to `top.add(grid)` i got a gds file that I can open in Klayout but with no content. Can you Help me to fix this issue?

**Comment by ourfool** [comment]
Hello @qd2d.
I guess the error may be due to Klayout 0.25.9. Can you send me a produced image.gds or an input image file?

**Comment by qd2d** [comment]
Thanks for your reply.  I managed to fix the problem. The error was due to a deprecated core.py script that I was using alongside the picToGds.py. The core.py script had some issues  such as usage of trailing Ls,  usage of `long(number)` instead of `int(number)` which is not supported in Python 3, and missing parenthesis. Also I had to replace <> with != in the core.py code. Your code works fine.
