### ISSUE TITLE
How to convert a image to GDS without any DRC issues 

### ISSUE THREAD

**Issue by tarunsai9966** [ourfool/picture-to-gds#5]
Is there any possibility to convert a image to GDS without any DRC issues for different technology nodes and for different foundaries.

**Comment by ourfool** [comment]
Hi
Each foundry has a different technology rule so I guess making a common GDS file for any foundries is hard work. Instead, you could make multiple GDS files for each foundry by changing command line arguments and running the script many times.

**Comment by tarunsai9966** [comment]
Hi,
Is there any way to include the rule deck in the python script to get a DRC free db.

**Comment by tarunsai9966** [comment]
Or else by including any SKILL script in python.....

**Comment by ourfool** [comment]
The information below may be helpful
https://community.cadence.com/cadence_technology_forums/f/pcb-skill/30223/call-python-program-from-skill
https://pypi.org/project/skillbridge/

**Comment by tarunsai9966** [comment]
Thanks for the help and quick response.... I will go through the above mentioned.....
